from treelib import Node, Tree
tree = Tree()
tree.create_node("Apakah kamu membutuhkan internet?", "q1")  # root node
tree.create_node("Apakah kamu berlokasi di perkotaan?", "q2", parent="q1")
tree.create_node("Apakah kamu berada di pulau jawa?", "q3", parent="q2")
tree.create_node("Apakah kamu berada di jabodetabek?", "q4", parent="q3")
tree.create_node("Apakah dilokasi kamu tersedia jaringan 4G?", "q5", parent="q4")
tree.create_node("Apakah kamu menggunakan internet hanya di satu lokasi?", "q6", parent="q5")
tree.create_node("Apakah kamu menggunakan internet untuk suatu instansi?", "q7", parent="q6")
tree.create_node("Rekomendasi Wi-fi Biznet / CBN", "q8", parent="q7")
# ---------------------------------
tree.create_node("Apakah kamu menggunakan untuk menonton tayangan Drama / Olahraga / Film?", "q9", parent="q7")
tree.create_node("Rekomendasi First media / Indihome / Biznet / XL / Smartfren", "q10", parent="q9")
tree.create_node("Apakah kamu akan menggunakan untuk bermain game?", "q11", parent="q9")
tree.create_node("Rekomendasi Biznet / My Republic / Telkomsel / XL", "q12", parent="q11")
tree.create_node("Rekomendasi Indihome / Oxygen / Indosat / Tri", "q13", parent="q11")
tree.create_node("Apakah kamu menggunakan untuk menonton tayangan Drama / Olahraga / Film?", "q14", parent="q6")
tree.create_node("Rekomendasi XL / Axis / Tri", "q15", parent="q14")
tree.create_node("Apakah kamu akan menggunakan untuk bermain game?", "q16", parent="q14")
tree.create_node("Rekomendasi XL / Axis / Smartfren", "q17", parent="q16")
tree.create_node("Rekomendasi Telkomsel / Indosat / XL", "q18", parent="q16")
tree.create_node("Apakah kamu bersedia untuk mengeluarkan dana lebih untuk ini?", "q19", parent="q5")
tree.create_node("Apakah pengguna sekitar ada yang memakai wifi?", "q20", parent="q19")
tree.create_node("Apakah kamu membutuhkan internet yang skala besar?", "q21", parent="q20")
tree.create_node("Apakah kamu menggunakan dalam jangka waktu lama?", "q22", parent="q21")
tree.create_node("Apakah kamu menggunakan untuk menonton tayangan Televisi?", "q23", parent="q22")
tree.create_node("Rekomendasi Indihome", "q24", parent="q23")
tree.create_node("Rekomendasi Vsat Satelite atau Data yang tersedia", "q25", parent="q23")
tree.create_node("Apakah kamu menggunakan untuk menonton tayangan Televisi?", "q26", parent="q22")
tree.create_node("Rekomendasi Indihome", "q27", parent="q26")
tree.create_node("Rekomendasi Vsat Satelite atau Data yang tersedia", "q28", parent="q26")
tree.create_node("Apakah kamu menggunakan dalam jangka waktu lama?", "q29", parent="q21")
tree.create_node("Apakah kamu menggunakan untuk menonton tayangan Televisi?", "q30", parent="q29")
tree.create_node("Rekomendasi Indihome", "q31", parent="q30")
tree.create_node("Rekomendasi Vsat Satelite atau Data yang tersedia", "q32", parent="q30")
# tree.create_node("", "", parent="")
tree.show()